swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8088'
basePath: /
tags:
  - name: employee-controller
    description: Employee Controller
paths:
  /employees:
    get:
      tags:
        - employee-controller
      summary: getAllEmployees
      operationId: getAllEmployeesUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Employee'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - employee-controller
      summary: saveEmployee
      operationId: saveEmployeeUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: employee
          description: employee
          required: true
          schema:
            $ref: '#/definitions/Employee'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Employee'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/employees/searchBy/{lastName}':
    get:
      tags:
        - employee-controller
      summary: searchBy
      operationId: searchByUsingGET
      produces:
        - '*/*'
      parameters:
        - name: lastName
          in: path
          description: lastName
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Employee'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/employees/{empId}':
    put:
      tags:
        - employee-controller
      summary: updateEmployee
      operationId: updateEmployeeUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: empId
          in: path
          description: empId
          required: true
          type: integer
          format: int64
        - in: body
          name: employee
          description: employee
          required: true
          schema:
            $ref: '#/definitions/Employee'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Employee'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - employee-controller
      summary: deleteEmployee
      operationId: deleteEmployeeUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: empId
          in: path
          description: empId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Employee'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
definitions:
  Employee:
    type: object
    properties:
      birthDate:
        type: string
        format: date
      empId:
        type: integer
        format: int64
      firstName:
        type: string
      gender:
        type: string
        enum:
          - F
          - M
      hireDate:
        type: string
        format: date
      lastName:
        type: string
    title: Employee
